name: pdbe_sifts
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - pip
  - ipython
  - setuptools
  - bioconda::mmseqs2
  - bioconda::blast
  - bioconda::fasta3
  - pip:
    - tqdm
    - biopython
    - funcy
    - lxml
    - requests
    - pandas
    - pymmseqs
    - coloredlogs
    - pyyaml
    - scikit-learn
    - ete4
    - omegaconf
    - gemmi
    - duckdb
    - platformdirs
    - python-dateutil
    - numpy