name: pdbe_sifts
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip
  - ipython
  - setuptools
  - mmseqs2
  - blast
  - fasta3
  - pip:
    - tqdm
    - biopython
    - funcy
    - lxml
    - requests
    - pandas
    - pymmseqs
    - coloredlogs
    - pyyaml
    - scikit-learn
    - ete4
    - omegaconf
    - gemmi
    - duckdb
    - dateparser
    - platformdirs
