logging:
  # Where to display the logs during a run
  destination: console

location:
  # base dir
  base: /hps/nobackup/pdbe/users/adamb/test_seg_gen/
  # Location where sifts will write outputs (please use an efficient disk space)
  nobackup_dir: /hps/nobackup/pdbe/users/adamb/test_seg_gen/
  # release dir
  nobackup_data_dir: ${location.nobackup_dir}/release/data

  work:
      base_dir: ${location.base}/release
      data_dir: ${location.work.base_dir}/data
      data_entry_dir: ${location.work.data_dir}/entry
      logs_dir: ${location.nobackup_dir}/release/logs/
      # chem_letter_mapping_file: ${location.work.data_dir}/others/three_to_one_letter_mapping.csv
      chem_letter_mapping_file: /hps/software/users/pdbe/user/adamb/pdbe_sifts/pdbe_sifts/input_files/three_to_one_letter_mapping.csv
      configs_dir: ${location.work.base_dir}/configs/release

cache:
  base: ${location.nobackup_dir}/release_data_cache/
  uniprot: ${cache.base}/uniprot # Local copies of uniprot files (XML, FASTA, JSON) + sifts UNP pickles

sifts_to_mmcif:
  clean_output_path: ${location.work.data_dir}/clean_mmcif_files/
  staging_dir: ${location.nobackup_data_dir}/sifts_only_cifs
  exchange_dir: null

sifts:
  base: ${location.work.data_dir}/sifts
  nf90_coverage: 0.7
  nobackup: ${location.nobackup_dir}/sifts/temp
  # tax_fix_pkl: ${cache.base}/nf90_tax_fix.pkl
  tax_fix_pkl: /hps/software/users/pdbe/user/adamb/pdbe_sifts/pdbe_sifts/input_files/nf90_taxid.pkl
  nf90_taxid_pkl: ${cache.base}/nf90_taxid.pkl
  nf90_coverage_pkl: ${cache.base}/nf90_coverage.pkl
  unp_url: https://www.uniprot.org/uniprot
  unp_filtered_mappings_file: ${sifts.nobackup}/idmapping_filtered.tab.gz
  csv_dir: ${sifts.base}
  report_dir: ${sifts.csv_dir}/reports
  res_csv: ${sifts.csv_dir}/res_csv
  seg_csv: ${sifts.csv_dir}/seg_csv
  nf90_csv: ${sifts.csv_dir}/nf90_csv
  results: ${sifts.nobackup}/results
  flatfiles: ${sifts.results}/flatfiles
  flatfiles_exchange: ${exchange.msd}/sifts/flatfiles
  split_xml: ${sifts.results}/split_xml
  pfam_dir: ${sifts.nobackup}/pfam
  ncbi_orthologs_url: https://ftp.ncbi.nih.gov/gene/DATA/
  scop2_url: https://www.ebi.ac.uk/pdbe/scop/files/


lists:
  entries_all: /hps/nobackup/pdbe/users/adamb/datasets/lists/entries_all
  entries_this_week: /hps/nobackup/pdbe/users/adamb/datasets/lists/entries_this_week
  sifts_mapping_changes: /hps/nobackup/pdbe/users/adamb/datasets/lists/sifts_mapping_changes.list
  sifts_modified_entries: /hps/nobackup/pdbe/users/adamb/datasets/lists/sifts_modified_entries

exchange:
  server: null
  username: null