#!/usr/bin/env python3
"""
Parser and scorer for TSV files generated by BLASTP or MMseqs2.

This module loads large or small alignment result files into a DuckDB database,
filters hits by identity, enriches them with UniProt metadata,
and computes adjusted, taxonomy-based, dataset, and SIFTS scores.
"""

import argparse
import os
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import duckdb
import pandas as pd

from pdbe_sifts.base.log import logger
from pdbe_sifts.global_mappings.scoring_function_helper import get_tax_weight
from pdbe_sifts.unp.unp import fetch_accessions

# Identity cutoff
IDENTITY_CUTOFF = 0.9

CREATE_TABLE_HITS = """
DROP TABLE IF EXISTS hits;

CREATE TABLE hits (
    entry                VARCHAR NOT NULL,
    entity               VARCHAR NOT NULL,
    accession            VARCHAR NOT NULL,
    alignment_len        INTEGER,
    query_len            INTEGER,
    mismatch             INTEGER,
    query_start          INTEGER,
    query_end            INTEGER,
    target_start         INTEGER,
    target_end           INTEGER,
    evalue               DOUBLE,
    bit_score            DOUBLE,
    identity             DOUBLE,
    coverage             DOUBLE,
    query_aligned        VARCHAR,
    target_aligned       VARCHAR,
    target_tax_id        INTEGER,
    query_tax_id         INTEGER,
    sifts_score          DOUBLE,
    pdb_cross_references INTEGER,
    adjusted_score       DOUBLE,
    tax_score            DOUBLE,
    dataset_score        DOUBLE
);
"""

# Read TSV from mmseqs2 with IDENTITY FILTER
INSERT_MMSEQS_TABLE_HITS = """
INSERT INTO hits (
    entry, entity, accession, alignment_len, query_len, mismatch,
    query_start, query_end, target_start, target_end,
    evalue, bit_score, identity, coverage,
    query_aligned, target_aligned, target_tax_id, query_tax_id,
    sifts_score, pdb_cross_references, adjusted_score, tax_score, dataset_score
)
SELECT
    -- Extract entry and entity from query (format: "entry-entity")
    SPLIT_PART(query, '-', 1) AS entry,
    SPLIT_PART(query, '-', 2) AS entity,
    target AS accession,
    alnlen AS alignment_len,
    qlen AS query_len,
    mismatch,
    qstart AS query_start,
    qend AS query_end,
    tstart AS target_start,
    tend AS target_end,
    evalue,
    bits AS bit_score,
    fident AS identity,
    qcov AS coverage,
    qaln AS query_aligned,
    taln AS target_aligned,
    taxid AS target_tax_id,
    -- Extract query_tax_id from qheader (format: "...TaxID=12345")
    CASE
        WHEN qheader IS NOT NULL AND qheader LIKE '%=%'
        THEN TRY_CAST(SPLIT_PART(qheader, '=', -1) AS INTEGER)
        ELSE NULL
    END AS query_tax_id,
    NULL AS sifts_score,
    NULL AS pdb_cross_references,
    NULL AS adjusted_score,
    NULL AS tax_score,
    NULL AS dataset_score
FROM read_csv(
    '{tsv_path}',
    columns={{
        'query':'VARCHAR',
        'target':'VARCHAR',
        'alnlen':'INTEGER',
        'mismatch':'INTEGER',
        'qstart':'INTEGER',
        'qend':'INTEGER',
        'tstart':'INTEGER',
        'tend':'INTEGER',
        'evalue':'DOUBLE',
        'bits':'DOUBLE',
        'qaln':'VARCHAR',
        'taln':'VARCHAR',
        'qlen':'INTEGER',
        'taxid':'INTEGER',
        'qheader':'VARCHAR',
        'fident':'DOUBLE',
        'qcov':'DOUBLE'
    }},
    delim='\\t',
    header=false
)
WHERE fident >= {identity_cutoff};
"""

# Read TSV from blastp with IDENTITY FILTER
INSERT_BLASTP_TABLE_HITS = """
INSERT INTO hits (
    entry, entity, accession, alignment_len, query_len, mismatch,
    query_start, query_end, target_start, target_end,
    evalue, bit_score, identity, coverage,
    query_aligned, target_aligned, target_tax_id, query_tax_id,
    sifts_score, pdb_cross_references, adjusted_score, tax_score, dataset_score
)
SELECT
    -- Extract entry and entity from qseqid (format: "entry-entity")
    SPLIT_PART(SPLIT_PART(qseqid, '|', 2), '-', 1) AS entry,
    CAST(SPLIT_PART(SPLIT_PART(qseqid, '|', 2), '-', 2) AS INTEGER) AS entity,
    SPLIT_PART(sseqid, '|', 2) AS accession,
    length AS alignment_len,
    qlen AS query_len,
    mismatch,
    qstart AS query_start,
    qend AS query_end,
    sstart AS target_start,
    send AS target_end,
    evalue,
    bitscore AS bit_score,
    pident / 100.0 AS identity,
    qcovs / 100.0 AS coverage,
    qseq AS query_aligned,
    sseq AS target_aligned,
    staxid AS target_tax_id,
    CASE
    WHEN qseqid IS NOT NULL AND qseqid LIKE '%=%'
    THEN TRY_CAST(SPLIT_PART(qseqid, '=', 2) AS INTEGER)
    ELSE NULL
    END AS query_tax_id,
    NULL AS sifts_score,
    NULL AS pdb_cross_references,
    NULL AS adjusted_score,
    NULL AS tax_score,
    NULL AS dataset_score
FROM read_csv(
    '{tsv_path}',
    columns={{
        'qseqid':'VARCHAR', 'sseqid':'VARCHAR', 'length':'INTEGER',
        'mismatch':'INTEGER',
        'qstart':'INTEGER','qend':'INTEGER',
        'sstart':'INTEGER','send':'INTEGER',
        'evalue':'DOUBLE','bitscore':'DOUBLE',
        'qseq':'VARCHAR','sseq':'VARCHAR','qlen':'INTEGER',
        'staxid':'INTEGER','pident':'DOUBLE','qcovs':'DOUBLE'
    }},
    delim='\\t',
    header=false
)
WHERE pident / 100.0 >= {identity_cutoff};
"""


def score_taxonomy_pair(args):
    """
    Worker function to compute taxonomy score for a pair of tax IDs.
    """
    query_taxid, target_taxid = args
    pair = (query_taxid, target_taxid)

    try:
        score = get_tax_weight(query_taxid, target_taxid)
        return {"query_tax_id": query_taxid, "target_tax_id": target_taxid, "tax_score": score}
    except Exception as e:
        logger.error(f"Error getting tax_weight for {pair}: {e}")
        return None


class GlobMappingsParser:
    """
    Parse and score global alignment results using DuckDB.

    This class:
      - Loads BLASTP or MMseqs2 TSV outputs into a DuckDB database
      - Applies identity filtering at load time
      - Computes adjusted alignment scores
      - Computes taxonomy-based scores using NCBI taxonomy
      - Enriches hits with UniProt-derived data
      - Produces a final SIFTS score per hit

    Designed to handle very large TSV files efficiently.
    """

    def __init__(
        self,
        format,
        result_file_path,
        out_dir,
        unp_csv=None,
        max_workers=None,
        identity_cutoff=IDENTITY_CUTOFF,
    ):
        self.format = format
        self.result_file_path = Path(result_file_path)
        self.out_dir = Path(out_dir)
        self.unp_csv = unp_csv
        self.identity_cutoff = identity_cutoff
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self.db_path = self.out_dir / "hits.duckdb"
        self.max_workers = max_workers or os.cpu_count()

    def _init_database(self):
        """
        Initialize the DuckDB database and load filtered hits from TSV.

        This method:
        - Drops and recreates the hits table
        - Loads TSV data using DuckDB CSV reader
        - Applies identity filtering at import time
        - Initializes the accession metadata table
        """
        conn = duckdb.connect(str(self.db_path))

        # Create table
        conn.execute(CREATE_TABLE_HITS)

        # Insert data with identity filter
        if self.format == "mmseqs":
            sql = INSERT_MMSEQS_TABLE_HITS.format(
                tsv_path=str(self.result_file_path), identity_cutoff=self.identity_cutoff
            )
        elif self.format == "blastp":
            sql = INSERT_BLASTP_TABLE_HITS.format(
                tsv_path=str(self.result_file_path), identity_cutoff=self.identity_cutoff
            )
        else:
            raise ValueError(f"Unsupported format: {self.format}")

        logger.info(f"Loading data with identity >= {self.identity_cutoff}...")
        conn.execute(sql)

        # Log how many rows were loaded
        count = conn.execute("SELECT COUNT(*) FROM hits").fetchone()[0]
        logger.info(f"Loaded {count} hits passing identity filter")

        conn.close()
        self.create_accession_table()

    def compute_adjusted_score(self):
        """
        Compute the adjusted alignment score for each hit.

        Formula:
        adjusted_score = (identity * coverage) * (1 - mismatch / query_len) * 1000

        Scores are set to 0 if required fields are missing.
        """
        logger.info("Computing adjusted_scores...")
        conn = duckdb.connect(str(self.db_path))

        conn.execute("""
            UPDATE hits
            SET adjusted_score =
                CASE
                    WHEN identity IS NULL
                    OR coverage IS NULL
                    OR mismatch IS NULL
                    OR query_len IS NULL
                    OR query_len = 0
                    THEN 0
                    ELSE (identity * coverage) * (1 - (mismatch::DOUBLE / query_len)) * 1000
                END
        """)

        logger.info("Adjusted score computed.")
        conn.close()

    def create_accession_table(self):
        """
        Create and populate the accession_info table.

        This method:
        - Creates the accession_info table if needed
        - Loads initial UniProt metadata from CSV if provided
        - Fetches missing accessions from UniProt
        - Computes dataset-level scores based on provenance and annotation score
        """
        conn = duckdb.connect(str(self.db_path))
        # 1) Create table
        conn.execute("""
            CREATE TABLE IF NOT EXISTS accession_info (
                accession VARCHAR,
                provenance VARCHAR,
                pdb_xref INTEGER,
                annotation_score DOUBLE,
                dataset_score DOUBLE
            );
        """)

        # 2) Load initial CSV if provided
        if self.unp_csv:
            conn.execute(
                """
                INSERT INTO accession_info
                SELECT
                    accession,
                    provenance,
                    pdb_xref,
                    annotation_score,
                    NULL AS dataset_score
                FROM read_csv(
                    ?,
                    delim=',',
                    header=true
                );
            """,
                [str(self.unp_csv)],
            )

        # 3) Find missing accessions from hits
        missing = [
            acc[0]
            for acc in conn.execute("""
            SELECT DISTINCT h.accession
            FROM hits h
            LEFT JOIN accession_info a
            ON h.accession = a.accession
            WHERE a.accession IS NULL
        """).fetchall()
        ]

        # 4) Fetch accession, provenance, annotation_score and number of pdb xrefs if any:
        if missing:
            rows = fetch_accessions(missing)
            df = pd.DataFrame(
                rows, columns=["accession", "provenance", "pdb_xref", "annotation_score"]
            )
            conn.register("tmp_accession_info", df)
            conn.execute("""
                INSERT INTO accession_info (accession, provenance, pdb_xref, annotation_score)
                SELECT accession, provenance, pdb_xref, annotation_score
                FROM tmp_accession_info
                WHERE accession NOT IN (
                    SELECT accession FROM accession_info
                );
            """)

            conn.unregister("tmp_accession_info")

        # 5) Compute dataset_score
        conn.execute("""
            UPDATE accession_info
            SET dataset_score =
                CASE
                    WHEN annotation_score IS NULL THEN 0
                    WHEN provenance = 'Swiss-Prot'
                        THEN 20 * annotation_score
                    ELSE
                        -50 + 10 * annotation_score
                END;
        """)

        conn.close()

    def compute_dataset_score(self):
        """Propagate dataset_score and pdb_cross_references from accession_info into hits."""
        conn = duckdb.connect(str(self.db_path))
        conn.execute("""
            UPDATE hits
            SET dataset_score = ai.dataset_score,
                pdb_cross_references = ai.pdb_xref
            FROM accession_info ai
            WHERE hits.accession = ai.accession;
        """)
        conn.close()

    def compute_sifts_score(self):
        """Compute final SIFTS score."""
        logger.info("Computing sifts_scores...")
        conn = duckdb.connect(str(self.db_path))
        conn.execute("""
            UPDATE hits
            SET sifts_score =
            COALESCE(adjusted_score, 0)
            + COALESCE(tax_score, 0)
            + COALESCE(dataset_score, 0)
            """)

        logger.info("SIFTS score computed.")

        conn.close()

    def compute_rank(self):
        """Assign a dense rank to each hit per (entry, entity), ordered by SIFTS score descending."""
        conn = duckdb.connect(self.db_path)
        conn.execute("""
            ALTER TABLE hits
            ADD COLUMN IF NOT EXISTS hit_rank INTEGER;
        """)
        conn.execute("""
            UPDATE hits
            SET hit_rank = ranked.hit_rank
            FROM (
                SELECT
                    rowid,
                    DENSE_RANK() OVER (
                        PARTITION BY entry, entity
                        ORDER BY
                            sifts_score DESC,
                            pdb_cross_references DESC
                    ) AS hit_rank
                FROM hits
            ) ranked
            WHERE hits.rowid = ranked.rowid;
        """)
        conn.close()

    def compute_tax_score(self):
        """Compute taxonomy scores for all distinct pairs of query_tax_id, target_tax_id"""
        conn = duckdb.connect(str(self.db_path))

        # Get distinct pairs, excluding NULL values
        pairs = conn.execute("""
            SELECT DISTINCT query_tax_id, target_tax_id
            FROM hits
            WHERE query_tax_id IS NOT NULL
            AND target_tax_id IS NOT NULL
        """).fetchall()

        conn.close()

        logger.info(f"Scoring {len(pairs)} taxonomy id pairs using {self.max_workers} workers")

        # Batch size for database updates
        DB_UPDATE_BATCH_SIZE = 5000
        all_updates = []

        with ProcessPoolExecutor(max_workers=self.max_workers) as pool:
            # Submit all tasks
            futures = {pool.submit(score_taxonomy_pair, pair): pair for pair in pairs}

            # Process results as they complete
            for i, fut in enumerate(as_completed(futures), 1):
                pair = futures[fut]
                try:
                    result = fut.result()

                    if result is not None:
                        all_updates.append(result)

                    # Batch update when we have enough results
                    if len(all_updates) >= DB_UPDATE_BATCH_SIZE:
                        self._batch_update_tax_scores(all_updates)
                        all_updates = []

                    if i % 1000 == 0:
                        logger.info(f"[{i}/{len(pairs)}] processed taxonomy pairs")

                except Exception as e:
                    logger.error(f"Error processing pair {pair}: {e}")

        # Process remaining updates
        if all_updates:
            self._batch_update_tax_scores(all_updates)

        logger.info("Taxonomy scoring complete!")

    def _batch_update_tax_scores(self, updates):
        """
        Helper method to batch update tax_scores in the database.
        """
        if not updates:
            return

        conn = duckdb.connect(str(self.db_path))

        try:
            df_updates = pd.DataFrame(updates)
            conn.register("tmp_tax_updates", df_updates)

            conn.execute("""
                UPDATE hits
                SET tax_score = tmp_tax_updates.tax_score
                FROM tmp_tax_updates
                WHERE hits.query_tax_id = tmp_tax_updates.query_tax_id
                AND hits.target_tax_id = tmp_tax_updates.target_tax_id
            """)

            logger.info(f"Updated {len(updates)} taxonomy score mappings in database")

        except Exception as e:
            logger.error(f"Error in batch update: {e}")
        finally:
            conn.close()

    def parse(self):
        """Main parsing pipeline"""
        self._init_database()
        self.compute_adjusted_score()
        self.compute_tax_score()
        self.compute_dataset_score()
        self.compute_sifts_score()
        self.compute_rank()
        logger.info(f"Parsed results ready at: {self.db_path}")


def main():
    parser = argparse.ArgumentParser(description="Parse BLAST/MMSEQS2 results")
    parser.add_argument("--format", choices=["mmseqs", "blastp"], required=True)
    parser.add_argument("--input", required=True, help="Path to TSV file")
    parser.add_argument("--output", required=True, help="Output directory")
    parser.add_argument("--unp-csv", help="Path to UniProt CSV file (optional)")
    parser.add_argument("--workers", type=int, help="Number of workers")
    parser.add_argument(
        "--identity-cutoff",
        type=float,
        default=IDENTITY_CUTOFF,
        help=f"Minimum identity (default: {IDENTITY_CUTOFF})",
    )

    args = parser.parse_args()

    parser_obj = GlobMappingsParser(
        format=args.format,
        result_file_path=args.input,
        out_dir=args.output,
        unp_csv=args.unp_csv,
        max_workers=args.workers,
        identity_cutoff=args.identity_cutoff,
    )

    parser_obj.parse()


if __name__ == "__main__":
    main()
